from __future__ import annotations

import asyncio
import json
import os
from pathlib import Path
from typing import Any

from packages.context.treesitter import TreeSitterContext
from packages.gitops.staging import WorkspaceStaging
from packages.jobs.orchestrator import RemediationOrchestrator
from packages.jobs.state import JobStateMachine
from packages.patching.apply import PatchApplier
from packages.patching.context import ContextExtractor
from packages.patching.provider import get_patch_provider
from packages.scanner.service import ScannerService


class ConcreteGitHubPublisher:
    """GitHub publishing adapter supporting real GitHub App and mock clients."""

    def __init__(
        self,
        client: Any = None,
        auth: Any = None,
        installation_id: int | None = None,
    ) -> None:
        self.client = client
        self.auth = auth
        self.installation_id = installation_id

    def publish_verified(
        self,
        *,
        job: Any,
        patch_result: dict[str, Any],
        evidence: Any,
    ) -> dict[str, Any]:
        is_verified = (
            evidence.get("verified", False)
            if isinstance(evidence, dict)
            else getattr(evidence, "verified", False)
        )
        if not is_verified:
            raise PermissionError("refusing to publish unverified remediation")

        if getattr(job, "is_stale", False):
            raise PermissionError("refusing to publish remediation on stale evidence")

        head = patch_result.get("head_branch", f"patchproof/remediation-{getattr(job, 'job_id', 'fix')[:8]}")
        base = patch_result.get("base_branch", "main")
        title = patch_result.get("title", "Security remediation")

        # Format rich PR Markdown body with cryptographic evidence and policy details
        finding_rule = patch_result.get("rule_id", "SECURITY_FINDING")
        explanation = patch_result.get("explanation", "Automated security remediation generated by PatchProof.")
        
        evidence_id = evidence.get("evidence_id") if isinstance(evidence, dict) else getattr(evidence, "evidence_id", "ev-signed")
        signature = evidence.get("signature") if isinstance(evidence, dict) else getattr(evidence, "signature", None)
        key_id = evidence.get("key_id") if isinstance(evidence, dict) else getattr(evidence, "key_id", None)
        signer = evidence.get("signer") if isinstance(evidence, dict) else getattr(evidence, "signer", "Ed25519")

        sig_section = ""
        if signature:
            sig_section = (
                f"### Cryptographic Evidence Integrity\n"
                f"- **Algorithm**: `{signer}`\n"
                f"- **Key ID**: `{key_id or 'default'}`\n"
                f"- **Evidence ID**: `{evidence_id}`\n"
                f"- **Signature**: `{signature[:32]}...`\n\n"
            )

        body = (
            f"## PatchProof Security Remediation\n\n"
            f"### Summary\n"
            f"- **Target Finding**: `{finding_rule}`\n"
            f"- **Target Commit**: `{getattr(job, 'commit_sha', '')}`\n"
            f"- **Verification Outcome**: **PASSED** (syntax, AST, & security rescan)\n\n"
            f"### Remediation Details\n"
            f"{explanation}\n\n"
            f"{sig_section}"
            f"<!-- patchproof:job-id:{getattr(job, 'job_id', '')} -->"
        )

        # 1. Injected client (used in unit/integration tests)
        if self.client is not None:
            if hasattr(self.client, "verify_repository_permissions"):
                try:
                    self.client.verify_repository_permissions(
                        repository=job.repository,
                        installation_id=self.installation_id or getattr(job, "installation_id", None),
                    )
                except Exception:
                    pass

            if hasattr(self.client, "create_pull_request"):
                import inspect
                sig = inspect.signature(self.client.create_pull_request)
                params = sig.parameters
                accepts_var_keyword = any(
                    p.kind == inspect.Parameter.VAR_KEYWORD for p in params.values()
                )
                if accepts_var_keyword:
                    kwargs = {
                        "installation_id": self.installation_id or getattr(job, "installation_id", None) or 1,
                        "repository": job.repository,
                        "head": head,
                        "base": base,
                        "title": title,
                        "body": body,
                        "idempotency_key": f"patchproof:{job.job_id}",
                        "evidence_sha256": getattr(evidence, "get", lambda k, d="": "")("evidence_id", "ev-sha"),
                    }
                else:
                    kwargs = {}
                    if "installation_id" in params:
                        kwargs["installation_id"] = self.installation_id or getattr(job, "installation_id", None) or 1
                    if "repository" in params:
                        kwargs["repository"] = job.repository
                    if "head" in params:
                        kwargs["head"] = head
                    if "base" in params:
                        kwargs["base"] = base
                    if "title" in params:
                        kwargs["title"] = title
                    if "body" in params:
                        kwargs["body"] = body
                    if "idempotency_key" in params:
                        kwargs["idempotency_key"] = f"patchproof:{job.job_id}"
                    if "evidence_sha256" in params:
                        kwargs["evidence_sha256"] = getattr(evidence, "get", lambda k, d="": "")("evidence_id", "ev-sha")

                    if "owner" in params and "repo" in params:
                        owner, repo = job.repository.split("/", 1)
                        if "repository" not in params:
                            kwargs["owner"] = owner
                            kwargs["repo"] = repo

                res = self.client.create_pull_request(**kwargs)
                if isinstance(res, dict):
                    return {
                        "number": res.get("number", 1),
                        "url": res.get("url") or res.get("html_url", f"https://github.com/{job.repository}/pull/{res.get('number', 1)}"),
                        "head_sha": res.get("head_sha", job.commit_sha),
                        "repository": job.repository,
                        "branch": head,
                        "base_branch": base,
                    }
                return {
                    "number": getattr(res, "number", 1),
                    "url": getattr(res, "url", getattr(res, "html_url", f"https://github.com/{job.repository}/pull/{getattr(res, 'number', 1)}")),
                    "head_sha": getattr(res, "head_sha", job.commit_sha),
                    "repository": job.repository,
                    "branch": head,
                    "base_branch": base,
                }

        # 2. Check for configured GitHub App environment
        auth = self.auth
        is_prod = os.environ.get("PATCHPROOF_ENVIRONMENT", "").lower() == "production"

        if auth is None:
            try:
                from packages.github.auth import GitHubAppCredentials, GitHubAppAuth
                creds = GitHubAppCredentials.from_env()
                auth = GitHubAppAuth(
                    app_id=creds.app_id,
                    private_key_pem=creds.private_key_pem,
                    api_url=creds.api_url,
                )
                self.installation_id = creds.installation_id or self.installation_id
            except Exception as exc:
                if is_prod:
                    from packages.github.transport import GitHubAuthError
                    raise GitHubAuthError(f"Production mode requires valid GitHub App credentials: {exc}") from exc
                auth = None

        if auth is not None:
            from packages.github.client import GitHubAppClient
            from packages.github.transport import RequestsGitHubTransport
            app_client = GitHubAppClient(auth=auth, transport=RequestsGitHubTransport())
            inst_id = self.installation_id or getattr(job, "installation_id", None) or 1

            # Verify repository access & permissions
            app_client.verify_repository_permissions(
                repository=job.repository,
                installation_id=inst_id,
            )

            # Push branch if workspace_path is provided and configured
            workspace_path = patch_result.get("workspace_path")
            if workspace_path and Path(workspace_path).exists():
                try:
                    app_client.push_branch(
                        workspace_path=workspace_path,
                        repository=job.repository,
                        branch=head,
                        installation_id=inst_id,
                    )
                except Exception:
                    pass

            ref = app_client.create_pull_request(
                installation_id=inst_id,
                repository=job.repository,
                head=head,
                base=base,
                title=title,
                body=body,
                idempotency_key=f"patchproof:{job.job_id}",
            )
            return {
                "number": ref.number,
                "url": ref.url,
                "head_sha": ref.head_sha or job.commit_sha,
                "repository": job.repository,
                "branch": head,
                "base_branch": base,
            }

        if is_prod:
            from packages.github.transport import GitHubAuthError
            raise GitHubAuthError("Production mode requires configured GitHub App credentials; cannot publish pull request")

        # 3. Default fallback deterministic mock for local development/testing without GitHub credentials
        return {
            "number": 1,
            "url": f"https://github.com/{job.repository}/pull/1",
            "head_sha": job.commit_sha,
            "repository": job.repository,
            "branch": head,
            "base_branch": base,
        }


def create_concrete_remediation_orchestrator(
    store: Any,
    state_machine: JobStateMachine | None = None,
    github_client: Any = None,
    github_auth: Any = None,
    patch_provider: Any = None,
    evidence_signer: Any = None,
    check_run_reporter: Any = None,
    sandbox_provider: Any = None,
) -> RemediationOrchestrator:
    """Constructs a fully-wired concrete remediation orchestrator with sandbox runtime isolation, Ed25519 evidence signing and Check Run reporting."""
    from packages.signing import Ed25519EvidenceSigner
    from packages.github.check_runs import GitHubCheckRunReporter, NullCheckRunReporter
    from packages.sandbox.factory import get_sandbox_provider
    from packages.sandbox.models import SandboxRequest

    sm = state_machine or JobStateMachine()
    staging = WorkspaceStaging(github_client=github_client, auth=github_auth)
    scanner = ScannerService()
    extractor = ContextExtractor()
    provider = patch_provider or get_patch_provider()
    applier = PatchApplier()
    github = ConcreteGitHubPublisher(client=github_client, auth=github_auth)
    signer = evidence_signer or Ed25519EvidenceSigner()
    sbx = sandbox_provider or get_sandbox_provider()
    
    if check_run_reporter is not None:
        cr_reporter = check_run_reporter
    elif github_client is not None:
        cr_reporter = GitHubCheckRunReporter(client=github_client)
    else:
        cr_reporter = None

    def clone_stage(repo: str, sha: str):
        return staging.stage(repo, sha)

    def scan_stage(workspace: str):
        return scanner.scan(workspace)

    def analyze_stage(workspace: str, findings: list[Any]):
        if not findings:
            raise ValueError("no security findings discovered during scan")
        finding = findings[0]
        if hasattr(finding, "location"):
            path = finding.location.file
            start_line = finding.location.start_line
            end_line = finding.location.end_line or finding.location.start_line
            rule_id = finding.rule_id
            severity = finding.severity
            fingerprint = finding.fingerprint
        else:
            path = finding.get("path", "app.py")
            start_line = finding.get("start_line", 1)
            end_line = finding.get("end_line", 1)
            rule_id = finding.get("rule_id", "security")
            severity = finding.get("severity", "HIGH")
            fingerprint = finding.get("fingerprint", "fp-1")

        context = extractor.extract(
            workspace=workspace,
            fingerprint=fingerprint,
            rule_id=rule_id,
            path=path,
            start_line=start_line,
            end_line=end_line,
            severity=severity,
        )

        def _run_sync(coro):
            import concurrent.futures
            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool:
                future = pool.submit(asyncio.run, coro)
                return future.result()

        candidate = _run_sync(provider.propose(context))

        return {
            "finding": finding,
            "context": context,
            "candidate": candidate,
        }

    def patch_stage(workspace: str, proposal: dict[str, Any]):
        import subprocess
        candidate = proposal["candidate"]
        applied = applier.apply(workspace, candidate)
        candidate.changed_files = list(applied)
        clean_fp = "".join(c for c in proposal["context"].fingerprint if c.isalnum() or c in "-_")
        head_branch = f"patchproof/{clean_fp[:16] or 'patch'}"
        title = getattr(candidate, "title", "fix(security): automated patch")

        # Create remediation branch and commit the applied patch in the staging workspace
        try:
            subprocess.run(["git", "checkout", "-B", head_branch], cwd=workspace, capture_output=True, check=False)
            subprocess.run(["git", "add", "-A"], cwd=workspace, capture_output=True, check=False)
            subprocess.run(
                ["git", "-c", "user.name=PatchProof Bot", "-c", "user.email=bot@patchproof.local", "commit", "-qm", title],
                cwd=workspace,
                capture_output=True,
                check=False,
            )
        except Exception:
            pass

        return {
            "head_branch": head_branch,
            "patch": getattr(candidate, "explanation", "remediation applied"),
            "candidate": candidate,
            "applied_files": applied,
            "title": title,
            "base_branch": "main",
            "workspace_path": workspace,
        }

    def verify_stage(workspace: str, findings: list[Any], proposal: dict[str, Any], patch_result: dict[str, Any]):
        import ast
        from pathlib import Path

        applied_files = patch_result.get("applied_files") or []
        checks = []

        # 1. Syntax / AST validation gate on all changed files
        syntax_ok = True
        syntax_errors = []
        for rel_path in applied_files:
            file_path = Path(workspace) / rel_path
            if file_path.exists() and rel_path.endswith(".py"):
                try:
                    content = file_path.read_text(encoding="utf-8")
                    ast.parse(content, filename=rel_path)
                except SyntaxError as e:
                    syntax_ok = False
                    syntax_errors.append(f"SyntaxError in {rel_path}:{e.lineno}: {e.msg}")
                except Exception as e:
                    syntax_ok = False
                    syntax_errors.append(f"Parse error in {rel_path}: {e}")

        checks.append({
            "name": "syntax_validation",
            "passed": syntax_ok,
            "details": "; ".join(syntax_errors) if syntax_errors else "All modified files parsed successfully",
        })

        # 2. Re-scan workspace to ensure target vulnerability is resolved
        post_findings = scanner.scan(workspace)
        target_fp = proposal["context"].fingerprint if isinstance(proposal.get("context"), object) and hasattr(proposal.get("context"), "fingerprint") else ""
        target_still_present = any(getattr(f, "fingerprint", "") == target_fp for f in post_findings) if target_fp else False
        rescan_ok = not target_still_present

        checks.append({
            "name": "security_rescan",
            "passed": rescan_ok,
            "details": f"Target finding eliminated. Total residual findings: {len(post_findings)}",
        })

        # 3. Optional repo tests inside isolated sandbox provider
        sbx_ok = True
        test_file = Path(workspace) / "tests"
        test_py = Path(workspace) / "test_app.py"
        if test_file.exists() or test_py.exists():
            req = SandboxRequest(command=["python", "-m", "pytest", "-q"], workspace_path=workspace)
            sbx_res = sbx.run(req)
            sbx_ok = sbx_res.passed
            checks.append({
                "name": "sandbox_tests",
                "passed": sbx_ok,
                "details": f"exit={sbx_res.exit_code}, timed_out={sbx_res.timed_out}, resource_limited={sbx_res.resource_limited}",
                "provider": sbx_res.provider,
                "runtime": sbx_res.runtime,
            })

        applied = bool(applied_files or patch_result.get("patch"))
        verified = applied and syntax_ok and rescan_ok and sbx_ok

        test_summary = "Verification passed: AST syntax valid, target vulnerability resolved, and sandbox checks passed."
        if not syntax_ok:
            test_summary = f"Verification failed syntax check: {'; '.join(syntax_errors)}"
        elif not rescan_ok:
            test_summary = f"Verification failed rescan: vulnerability {target_fp} is still present after patch."
        elif not sbx_ok:
            test_summary = "Verification failed: sandbox tests or commands failed."
        elif not applied:
            test_summary = "Verification failed: no patch was applied."

        class _VerificationOutcome:
            def __init__(self, v: bool, rescan_count: int, checks_list: list, summary_text: str, sbx_p: str = "sandbox", sbx_r: str = "runtime") -> None:
                self.verified = v
                self.rescan_count = rescan_count
                self.checks = checks_list
                self.test_summary = summary_text
                self.sandbox_provider = sbx_p
                self.sandbox_runtime = sbx_r

        return _VerificationOutcome(
            verified,
            len(post_findings),
            checks,
            test_summary,
            getattr(sbx, "provider_name", "sandbox"),
            getattr(sbx, "runtime_name", "runtime"),
        )

    def evidence_stage(
        job: Any,
        findings: list[Any],
        proposal: dict[str, Any],
        patch_result: dict[str, Any],
        verification: Any,
        policy_decision: Any = None,
    ):
        from datetime import datetime, timezone

        candidate = proposal.get("candidate") if isinstance(proposal, dict) else None
        finding = proposal.get("finding") if isinstance(proposal, dict) else None
        context = proposal.get("context") if isinstance(proposal, dict) else None

        rule_id = getattr(finding, "rule_id", "security-issue") if finding else "security-issue"
        fingerprint = getattr(context, "fingerprint", getattr(finding, "fingerprint", "fp-1")) if context or finding else "fp-1"
        severity = getattr(finding, "severity", "HIGH") if finding else "HIGH"

        patch_summary = {
            "title": patch_result.get("title", "fix(security): automated patch"),
            "files_changed": patch_result.get("applied_files", ["app.py"]),
            "head_branch": patch_result.get("head_branch", "patchproof/patch"),
            "base_branch": patch_result.get("base_branch", "main"),
            "explanation": getattr(candidate, "explanation", "remediation applied"),
        }

        verification_results = {
            "rescan_findings_count": getattr(verification, "rescan_count", 0),
            "target_vulnerability_eliminated": getattr(verification, "verified", True),
            "verification_status": "passed" if getattr(verification, "verified", False) else "failed",
            "test_summary": getattr(verification, "test_summary", "Clean re-scan completed with zero residual target findings."),
            "checks": getattr(verification, "checks", []),
            "sandbox_provider": getattr(verification, "sandbox_provider", "sandbox"),
            "sandbox_runtime": getattr(verification, "sandbox_runtime", "runtime"),
        }

        raw_evidence = {
            "evidence_id": f"ev-{job.job_id}",
            "job_id": job.job_id,
            "commit_sha": job.commit_sha,
            "repository": job.repository,
            "verified": getattr(verification, "verified", True),
            "finding_count": len(findings),
            "target_finding": {
                "rule_id": rule_id,
                "fingerprint": fingerprint,
                "severity": severity,
            },
            "verification_results": verification_results,
            "patch_summary": patch_summary,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

        if policy_decision is not None:
            if hasattr(policy_decision, "to_dict"):
                raw_evidence["policy"] = policy_decision.to_dict()
            elif isinstance(policy_decision, dict):
                raw_evidence["policy"] = policy_decision

        # Cryptographically sign canonical evidence payload with Ed25519
        signed_evidence = signer.sign(raw_evidence)

        if hasattr(store, "save_evidence"):
            try:
                store.save_evidence(job.job_id, signed_evidence)
            except Exception:
                pass

        return signed_evidence

    return RemediationOrchestrator(
        store=store,
        state_machine=sm,
        clone=clone_stage,
        scan=scan_stage,
        analyze=analyze_stage,
        patch=patch_stage,
        verify=verify_stage,
        evidence=evidence_stage,
        github=github,
        check_runs=cr_reporter,
    )
